### ISSUE TITLE
tea section

### ISSUE THREAD

**Issue by rimmesbe** [Craft4Coffee/teacozy#1]
You are splitting this section up into rows which are going to make the site very rigid and non-responsive. Instead, you want to create tea components (image + text for that image) and then use flex display on the parent of these components to lay them out. Flex display will replace the need for rows because it automatically wraps content that won't fit onto a new line and centers it.

You could even look into `<figure>` tags for the tea components.

https://github.com/Craft4Coffee/teacozy/blob/master/index.html#L51-L71

**Comment by Craft4Coffee** [comment]
Thank you. I did this intentionally because I could not get the flex display components to work properly. After working with this particular area for much too long, I had to move on.

**Comment by Craft4Coffee** [comment]
I plan on going back and updating the css with your suggestions. Thank you again!
